@extends('layouts.marketing')
@section('title', $details['name'].' features')
@section('content')
<main class="module-page module-page--{{ $details['accent'] }}">
    <section class="module-hero"><div class="container module-hero__grid"><div><a href="{{ route('features') }}" class="back-link">← All features</a><span class="eyebrow eyebrow--dark">{{ strtoupper($details['tag']) }} · {{ strtoupper($details['name']) }}</span><h1>{{ $details['headline'] }}</h1><p>{{ $details['intro'] }}</p><div class="hero-actions"><a href="{{ route('register') }}" class="button button--primary">Start with {{ $details['name'] }} →</a><a href="#features" class="button button--secondary">Explore features</a></div></div><div class="module-visual"><span class="module-visual__tag">{{ $details['tag'] }}</span><div class="module-visual__panel"><div class="module-visual__top"><i></i><i></i><i></i></div><div class="module-visual__content"><span></span><b>{{ $details['name'] }}</b><p>{{ $details['outcome'] }}</p><div><i></i><i></i><i></i></div></div></div><div class="module-visual__signal">✓ Ready to launch</div></div></div></section>
    <section class="module-promise"><div class="container"><span>THE OUTCOME</span><p>{{ $details['outcome'] }}</p></div></section>
    <section class="section module-capabilities" id="features"><div class="container"><div class="section-heading section-heading--split"><div><span class="eyebrow eyebrow--dark">WHAT'S INCLUDED</span><h2>Everything you need to make {{ strtolower($details['tag']) }} work.</h2></div><p>Purpose-built capabilities in one focused module, connected to the same workspace as the rest of your customer journey.</p></div><div class="capability-grid">@foreach($details['features'] as $index => $feature)<article><span>{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</span><h3>{{ $feature[0] }}</h3><p>{{ $feature[1] }}</p></article>@endforeach</div></div></section>
    <section class="module-steps"><div class="container"><div class="section-heading"><span class="eyebrow">FROM IDEA TO LIVE</span><h2>Simple to start.<br>Easy to run.</h2></div><div class="step-grid">@foreach($details['steps'] as $index => $step)<article><span>0{{ $index + 1 }}</span><h3>{{ $step[0] }}</h3><p>{{ $step[1] }}</p></article>@endforeach</div></div></section>
    <section class="section related-modules"><div class="container"><div class="related-heading"><div><span class="eyebrow eyebrow--dark">KEEP BUILDING</span><h2>Connect your next customer touchpoint.</h2></div><a href="{{ route('features') }}" class="text-link">View all modules →</a></div><div class="related-grid">@foreach(collect(config('marketing_modules'))->except($module)->take(3) as $slug => $related)<a href="{{ route('modules.show', $slug) }}"><span>{{ $related['tag'] }}</span><h3>{{ $related['name'] }}</h3><p>{{ $related['headline'] }}</p><b>Explore →</b></a>@endforeach</div></div></section>
    <section class="section final-cta"><div class="container"><div class="final-cta__card"><span class="eyebrow eyebrow--dark">YOUR NEXT STEP</span><h2>Put {{ $details['name'] }} to work.</h2><p>Launch this module inside a connected customer-growth workspace.</p><a href="{{ route('register') }}" class="button button--primary">Create your workspace →</a></div></div></section>
</main>
@endsection
