@extends('layouts.app')
@section('title','AI Autoblog')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">AI Autoblog</h1><p class="text-muted mb-0">Generate, review and publish original content to WordPress or any REST-enabled platform.</p></div><span class="badge bg-primary">{{ strtoupper($ai['provider']) }}</span></div>
<ul class="nav nav-tabs mb-4" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#posts">Generate</button></li><li class="nav-item"><a class="nav-link" href="{{ route('autoblog.posts.index') }}">Posts</a></li><li class="nav-item"><a class="nav-link" href="{{ route('autoblog.destinations.index') }}">Destinations</a></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#ai-settings">AI Settings</button></li></ul>
<div class="tab-content"><div class="tab-pane fade show active" id="posts">
<div class="card mb-4"><div class="card-body"><div class="d-flex justify-content-between align-items-center"><h5>Generate a new article</h5><span class="badge">Default AI: {{ strtoupper($ai['provider']) }}</span></div><form method="POST" action="{{ route('autoblog.posts.store') }}">@csrf<div class="row g-3"><div class="col-md-6"><label class="form-label">Topic</label><input name="topic" value="{{ old('topic') }}" required class="form-control" placeholder="How small businesses can improve customer retention"></div><div class="col-md-3"><label class="form-label">Tone</label><select name="tone" class="form-select"><option>Professional</option><option>Friendly</option><option>Authoritative</option><option>Conversational</option></select></div><div class="col-md-3"><label class="form-label">Saved destination (optional)</label><select name="destination_id" class="form-select"><option value="">None — keep as draft</option>@foreach($destinations as $d)<option value="{{ $d->id }}" @selected(old('destination_id')==$d->id)>{{ $d->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">SEO keywords</label><input name="keywords" value="{{ old('keywords') }}" class="form-control" placeholder="retention, customer loyalty, small business"></div><div class="col-md-6"><label class="form-label">Custom destination URL (optional)</label><input type="url" name="destination_url" value="{{ old('destination_url') }}" class="form-control" placeholder="https://example.com/api/posts"><div class="form-text">Used when no saved destination is selected.</div></div><div class="col-md-6"><label class="form-label">Publish schedule (optional)</label><input type="datetime-local" name="scheduled_at" value="{{ old('scheduled_at') }}" class="form-control"></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary w-100">Queue AI generation</button></div></div></form><div class="small text-muted mt-3">Leave both destination fields empty to generate a draft. Generation uses the <code>autoblog</code> queue; Cron checks scheduled posts every minute and Reverb delivers live status updates.</div></div></div>
@forelse($posts as $post)<div class="card mb-3"><div class="card-body"><div class="d-flex justify-content-between"><div><span class="badge bg-{{ $post->status==='published'?'success':($post->status==='failed'?'danger':'secondary') }}">{{ ucfirst($post->status) }}</span><h5 class="mt-2">{{ $post->title ?: $post->topic }}</h5><small class="text-muted">{{ $post->provider }} · {{ $post->destination?->name ?? 'No destination' }} · {{ $post->created_at->diffForHumans() }}</small></div>@if($post->external_url)<a href="{{ $post->external_url }}" target="_blank" rel="noopener" class="btn btn-sm btn-outline-success align-self-start">View published</a>@endif</div>@if($post->last_error)<div class="alert alert-danger mt-3">{{ $post->display_error }}</div>@endif
@if($post->excerpt)<p class="text-muted mt-3 mb-0">{{ Str::limit($post->excerpt, 220) }}</p>@endif
<div class="mt-3"><a href="{{ route('autoblog.posts.show',$post) }}" class="btn btn-primary">{{ $post->content ? 'Open generated post' : 'View details' }}</a></div>
<div class="d-flex gap-2 mt-2">@if(($post->destination || $post->destination_url) && $post->content)<form method="POST" action="{{ route('autoblog.posts.publish',$post) }}">@csrf<button class="btn btn-success">Queue Publish</button></form>@endif
@if($post->status==='failed')<form method="POST" action="{{ route('autoblog.posts.retry',$post) }}">@csrf<button class="btn btn-outline-primary">Retry Generation</button></form>@endif
<form method="POST" action="{{ route('autoblog.posts.destroy',$post) }}" onsubmit="return confirm('Delete this post?')">@csrf @method('DELETE')<button class="btn btn-outline-danger">Delete</button></form></div></div></div>@empty<div class="text-center text-muted py-5">No articles yet.</div>@endforelse{{ $posts->links() }}</div>
<div class="tab-pane fade" id="destinations"><div class="card"><div class="card-body"><h5>Add publishing destination</h5><form method="POST" action="{{ route('autoblog.destinations.store') }}">@csrf<div class="row g-3"><div class="col-md-4"><label class="form-label">Name</label><input name="name" required class="form-control"></div><div class="col-md-4"><label class="form-label">Platform</label><select name="type" class="form-select"><option value="wordpress">WordPress REST API</option><option value="webhook">Generic REST webhook</option></select></div><div class="col-md-4"><label class="form-label">URL</label><input name="base_url" type="url" required class="form-control" placeholder="https://example.com"></div><div class="col-md-6"><label class="form-label">WordPress username (optional for webhook)</label><input name="username" class="form-control"></div><div class="col-md-6"><label class="form-label">Application password / bearer token</label><input name="secret" type="password" required class="form-control"></div></div><input type="hidden" name="is_active" value="1"><button class="btn btn-primary mt-3">Add Destination</button></form></div></div>@foreach($destinations as $d)<div class="card mt-3"><div class="card-body d-flex justify-content-between"><div><strong>{{ $d->name }}</strong><div class="small text-muted">{{ ucfirst($d->type) }} · {{ $d->base_url }}</div></div><form method="POST" action="{{ route('autoblog.destinations.destroy',$d) }}" onsubmit="return confirm('Delete destination?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></div></div>@endforeach</div>
<div class="tab-pane fade" id="ai-settings"><div class="card"><div class="card-body"><h5>AI provider</h5><p class="text-muted">These credentials are shared with the workspace AI assistant and stored securely.</p><form method="POST" action="{{ route('autoblog.settings.update') }}">@csrf @method('PUT')<div class="mb-3"><label class="form-label">Provider</label><select name="provider" class="form-select"><option value="openai" @selected($ai['provider']==='openai')>OpenAI</option><option value="kimi" @selected($ai['provider']==='kimi')>Kimi K3 (Moonshot)</option></select></div><h6>OpenAI</h6><div class="row g-3 mb-4"><div class="col-md-4"><input type="password" name="openai_key" class="form-control" placeholder="{{ $ai['openai']['key_hint'] ?: 'API key' }}"></div><div class="col-md-4"><select name="openai_model" class="form-select">@foreach($openaiModels as $value=>$label)<option value="{{ $value }}" @selected($ai['openai']['model']===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><input type="url" name="openai_base_url" class="form-control" value="{{ $ai['openai']['base_url'] }}"></div></div><h6>Kimi K3</h6><div class="row g-3"><div class="col-md-4"><input type="password" name="kimi_key" class="form-control" placeholder="{{ $ai['kimi']['key_hint'] ?: 'API key' }}"></div><div class="col-md-4"><select name="kimi_model" class="form-select">@foreach($kimiModels as $value=>$label)<option value="{{ $value }}" @selected($ai['kimi']['model']===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><input type="url" name="kimi_base_url" class="form-control" value="{{ $ai['kimi']['base_url'] }}"></div></div><button class="btn btn-primary mt-4">Save AI Settings</button></form></div></div></div></div>
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const refresh=()=>window.location.reload();
 if(window.Echo){window.Echo.private('tenant.{{ currentTenant()->id }}.autoblog').listen('.autoblog.post.updated',refresh);}
 @if($posts->contains(fn($post)=>in_array($post->status,['queued','generating','scheduled','publish_queued','publishing'])))
 setTimeout(refresh,15000);
 @endif
});
</script>
@endpush
@endsection
