<?php
namespace App\Http\Controllers\Forms;
use App\Http\Controllers\Controller; use App\Models\Form; use App\Models\FormSite; use App\Models\Tenant; use App\Services\Forms\PublicAssetService; use App\Services\Forms\SubmissionService; use Illuminate\Http\Request;
class EmbedController extends Controller {
 public function __construct(protected PublicAssetService $assets,protected SubmissionService $submissions){}
 protected function site(Request $r):FormSite{return $r->attributes->get('form_site');} protected function tenant(Request $r):Tenant{return $r->attributes->get('tenant');}
 protected function origin(Request $r,FormSite $s):void{$o=$r->header('Origin')?:($r->header('Referer')?(parse_url($r->header('Referer'),PHP_URL_SCHEME).'://'.parse_url($r->header('Referer'),PHP_URL_HOST)):null);abort_unless($s->allowsOrigin($o),403);}
 public function boot(Request $r,string $siteKey){$s=$this->site($r);$this->origin($r,$s);$payload='window.__F='.json_encode(['k'=>$s->public_key,'b'=>rtrim(url('/f/'.$s->public_key),'/'),'c'=>$s->brandColor()],JSON_UNESCAPED_SLASHES).';';$css=$this->assets->stylesheet();if($css!=='')$payload.='(function(){var s=document.createElement("style");s.textContent='.json_encode($css).';document.head.appendChild(s);})();';return response($payload."\n".$this->assets->javascript(),200,['Content-Type'=>'application/javascript; charset=utf-8','Access-Control-Allow-Origin'=>'*']);}
 public function config(Request $r){$s=$this->site($r);$this->origin($r,$s);return response()->json(['c'=>$s->brandColor(),'i'=>Form::withoutGlobalScopes()->where('tenant_id',$this->tenant($r)->id)->where('form_site_id',$s->id)->where('status','live')->get()->map->toPublicPayload()->values()],200,['Access-Control-Allow-Origin'=>'*']);}
 public function submit(Request $r){$s=$this->site($r);$this->origin($r,$s);if(filled($r->input('website')))return response()->json(['ok'=>true]);$v=$r->validate(['i'=>['required','integer'],'answers'=>['required','array'],'page_url'=>['nullable','string','max:2000']]);$form=Form::withoutGlobalScopes()->where('tenant_id',$this->tenant($r)->id)->where('form_site_id',$s->id)->where('id',$v['i'])->where('status','live')->firstOrFail();foreach($form->fields as $field){$value=$v['answers'][$field['key']]??null;if(!empty($field['required'])&&blank($value))abort(422);if(($field['type']??'')==='email'&&filled($value)&&!filter_var($value,FILTER_VALIDATE_EMAIL))abort(422);}$this->submissions->capture($this->tenant($r),$form,$v['answers'],$v['page_url']??null);return response()->json(['ok'=>true,'thank_you'=>$form->thank_you],201,['Access-Control-Allow-Origin'=>'*']);}
 public function preflight(){return response('',204,['Access-Control-Allow-Origin'=>'*','Access-Control-Allow-Methods'=>'GET, POST, OPTIONS','Access-Control-Allow-Headers'=>'Content-Type, Accept']);}
}
