<?php
namespace App\Http\Controllers\Autoblog;
use App\Http\Controllers\Controller; use App\Jobs\GenerateAutoblogPost; use App\Jobs\PublishAutoblogPost; use App\Models\AutoblogDestination; use App\Models\AutoblogPost; use App\Services\Chat\AiSettingsService; use Illuminate\Http\Request;
class PostController extends Controller {
 public function index(Request $r){$status=$r->string('status')->toString();$query=AutoblogPost::with('destination')->latest();if($status&&$status!=='all'){$statuses=$status==='generated'?['draft']:($status==='scheduled'?['scheduled','publish_queued']:($status==='published'?['published']:[]));if($statuses)$query->whereIn('status',$statuses);}return view('autoblog.posts.index',['posts'=>$query->paginate(20)->withQueryString(),'status'=>$status?:'all','counts'=>['all'=>AutoblogPost::count(),'generated'=>AutoblogPost::where('status','draft')->count(),'scheduled'=>AutoblogPost::whereIn('status',['scheduled','publish_queued'])->count(),'published'=>AutoblogPost::where('status','published')->count()]]);}
 public function show(AutoblogPost $post){return view('autoblog.posts.show',['post'=>$post->load('destination')]);}
 public function store(Request $r, AiSettingsService $ai){ $v=$r->validate(['topic'=>'required|string|max:500','tone'=>'required|string|max:80','keywords'=>'nullable|string|max:500','destination_id'=>'nullable|exists:autoblog_destinations,id','destination_url'=>'nullable|url:http,https|max:2000','scheduled_at'=>'nullable|date|after:now']);$post=AutoblogPost::create(['topic'=>$v['topic'],'tone'=>$v['tone'],'keywords'=>$v['keywords']??null,'destination_id'=>$v['destination_id']??null,'destination_url'=>$v['destination_url']??null,'scheduled_at'=>$v['scheduled_at']??null,'created_by'=>$r->user()->id,'provider'=>$ai->for(currentTenant())['provider'],'status'=>'queued']);GenerateAutoblogPost::dispatch($post->id);return back()->with('success','Article queued for AI generation. You can leave this page safely.'); }
 public function update(Request $r,AutoblogPost $post){$post->update($r->validate(['title'=>'required|string|max:255','slug'=>'required|string|max:255','excerpt'=>'nullable|string|max:1000','content'=>'required|string']));return back()->with('success','Draft saved.');}
 public function publish(AutoblogPost $post){if((!$post->destination||!$post->destination->is_active)&&blank($post->destination_url))return back()->with('error','Choose a saved destination or enter an optional destination URL.');if($post->destination&&blank($post->destination->verified_at))return back()->with('error','Verify the destination connection before publishing.');$post->update(['status'=>'publish_queued','last_error'=>null]);PublishAutoblogPost::dispatch($post->id);return back()->with('success','Post queued for publishing.');}
 public function retry(AutoblogPost $post){$post->update(['status'=>'queued','last_error'=>null]);GenerateAutoblogPost::dispatch($post->id);return back()->with('success','Generation queued again.');}
 public function destroy(AutoblogPost $post){$post->delete();return back()->with('success','Post deleted.');}
}
