<?php

return [
    'live-chat' => [
        'name' => 'Live Chat', 'tag' => 'Conversation', 'accent' => 'blue',
        'headline' => 'Turn quick questions into lasting relationships.',
        'intro' => 'Meet visitors in the moment with a fast, branded chat experience and give your team the context to respond with confidence.',
        'outcome' => 'Resolve questions faster, qualify intent while it is fresh, and keep every conversation organized in one shared inbox.',
        'features' => [
            ['Shared team inbox', 'Assign, prioritize, and manage every conversation without duplicated replies.'],
            ['Branded chat widget', 'Match your website and control the welcome message, launcher, and availability.'],
            ['Knowledge base', 'Give customers instant answers and help agents find accurate information quickly.'],
            ['Canned responses', 'Save your best answers and respond consistently in a few clicks.'],
            ['Files and attachments', 'Let customers and agents share the context needed to solve an issue.'],
            ['Reports and availability', 'Track response performance and set clear online hours for your team.'],
        ],
        'steps' => [['Install', 'Add one lightweight snippet to your website.'], ['Connect', 'Visitors start a conversation from any page.'], ['Resolve', 'Your team responds with shared context and tools.']],
    ],
    'email-marketing' => [
        'name' => 'Email Marketing', 'tag' => 'Nurture', 'accent' => 'violet',
        'headline' => 'Keep the conversation going after they leave.',
        'intro' => 'Build an audience you own, send focused campaigns, and learn which messages move subscribers to act.',
        'outcome' => 'Turn captured interest into repeat visits and revenue with organized lists, reusable campaigns, and clear engagement data.',
        'features' => [
            ['Subscriber management', 'Organize contacts, status, and consent across focused mailing lists.'],
            ['Reusable templates', 'Create consistent emails faster with a library your whole team can use.'],
            ['Campaign builder', 'Compose, preview, schedule, and send polished campaigns from one workspace.'],
            ['Audience imports', 'Bring in existing subscribers and CRM contacts without losing organization.'],
            ['Open and click tracking', 'See how each campaign performs and which links earn attention.'],
            ['Unsubscribe handling', 'Respect subscriber choices with built-in public preference flows.'],
        ],
        'steps' => [['Organize', 'Import contacts and build focused lists.'], ['Create', 'Write once and reuse proven templates.'], ['Learn', 'Measure engagement and improve the next send.']],
    ],
    'engage' => [
        'name' => 'Engage', 'tag' => 'Convert', 'accent' => 'coral',
        'headline' => 'Show the right message at exactly the right moment.',
        'intro' => 'Create targeted onsite campaigns that respond to visitor behavior instead of interrupting everyone with the same popup.',
        'outcome' => 'Convert more sessions into leads and offers with precise timing, page rules, templates, and measurable results.',
        'features' => [
            ['Campaign templates', 'Start quickly with proven layouts for leads, offers, announcements, and guides.'],
            ['Behavior triggers', 'Launch campaigns based on delay, scroll, exit intent, or visitor activity.'],
            ['Page targeting', 'Show relevant campaigns only on matching URLs and customer journeys.'],
            ['Lead capture', 'Collect visitor details directly inside each campaign experience.'],
            ['Scheduling and status', 'Prepare campaigns ahead of time and control when they are active.'],
            ['Performance reporting', 'Compare views, interactions, leads, and conversion rates.'],
        ],
        'steps' => [['Design', 'Choose a template and make it yours.'], ['Target', 'Define the pages and moments that matter.'], ['Convert', 'Capture intent and measure every result.']],
    ],
    'forms' => [
        'name' => 'Forms', 'tag' => 'Capture', 'accent' => 'cyan',
        'headline' => 'Make it effortless for customers to raise their hand.',
        'intro' => 'Build focused forms for leads, contact requests, surveys, and custom workflows—then manage every response centrally.',
        'outcome' => 'Collect cleaner customer data without a separate form service or a spreadsheet full of disconnected submissions.',
        'features' => [
            ['Flexible form builder', 'Combine text, email, choices, dates, and long-form responses for any workflow.'],
            ['Ready-made templates', 'Launch contact, lead, survey, and custom forms without starting from zero.'],
            ['Embeddable experience', 'Add responsive forms to any website with a simple installation snippet.'],
            ['Submission inbox', 'Review every response with its status and customer context in one place.'],
            ['CSV exports', 'Move form results into analysis or operational workflows whenever needed.'],
            ['Custom thank-you flows', 'Give every respondent a clear, branded next step after submission.'],
        ],
        'steps' => [['Build', 'Choose fields and shape the experience.'], ['Embed', 'Publish the form wherever customers engage.'], ['Act', 'Review, qualify, and export submissions.']],
    ],
    'reviews' => [
        'name' => 'Reviews', 'tag' => 'Trust', 'accent' => 'gold',
        'headline' => 'Turn happy customers into visible proof.',
        'intro' => 'Collect thoughtful feedback through a branded flow, moderate responses, and publish your best customer voices.',
        'outcome' => 'Build trust where buying decisions happen with a repeatable review process and an always-current website widget.',
        'features' => [
            ['Branded review flow', 'Give customers a focused, mobile-friendly place to share their experience.'],
            ['Star ratings and feedback', 'Capture both quick sentiment and the story behind each score.'],
            ['Moderation controls', 'Review incoming feedback and decide what appears publicly.'],
            ['Embeddable review widget', 'Display approved reviews anywhere on your website.'],
            ['Collection links', 'Share a direct review request through email, chat, or post-purchase flows.'],
            ['Review management', 'Search and organize customer feedback from one workspace.'],
        ],
        'steps' => [['Request', 'Share your branded review link.'], ['Moderate', 'Review feedback and approve the best stories.'], ['Publish', 'Display trusted proof on high-intent pages.']],
    ],
    'bookings' => [
        'name' => 'Bookings', 'tag' => 'Schedule', 'accent' => 'green',
        'headline' => 'Let customers book the next step while interest is high.',
        'intro' => 'Offer services, show real availability, and make scheduling easy without the back-and-forth.',
        'outcome' => 'Turn intent into confirmed appointments with a polished booking flow, reminders, and customer self-service.',
        'features' => [
            ['Service management', 'Define durations, descriptions, locations, and booking details for each service.'],
            ['Availability rules', 'Control working hours and protect time that should never be booked.'],
            ['Public booking page', 'Give customers a responsive, branded path from service to confirmation.'],
            ['Appointment management', 'Review upcoming and past bookings with all customer details attached.'],
            ['Calendar links', 'Provide downloadable calendar events and feed access for easier planning.'],
            ['Reminders and self-service', 'Help customers remember, manage, and update their own appointments.'],
        ],
        'steps' => [['Configure', 'Add services and define availability.'], ['Share', 'Embed or link to your booking experience.'], ['Meet', 'Manage confirmed appointments from one view.']],
    ],
    'social-proof' => [
        'name' => 'Social Proof', 'tag' => 'Confidence', 'accent' => 'orange',
        'headline' => 'Make real customer activity impossible to miss.',
        'intro' => 'Show timely, credible activity notifications while visitors browse and turn quiet momentum into visible confidence.',
        'outcome' => 'Reduce uncertainty on high-intent pages by demonstrating that other people are already choosing and trusting you.',
        'features' => [
            ['Activity notifications', 'Display recent conversions, signups, bookings, or other meaningful events.'],
            ['Branded widget', 'Control the appearance and placement so notifications feel native to your site.'],
            ['Event collection', 'Record real activity through your workspace and installation script.'],
            ['Display controls', 'Set timing, frequency, and behavior for a helpful—not distracting—experience.'],
            ['Website installation', 'Go live with one lightweight snippet and a site-specific configuration.'],
            ['Performance overview', 'Understand how proof appears across the visitor experience.'],
        ],
        'steps' => [['Connect', 'Install the script on your website.'], ['Collect', 'Record meaningful customer activity.'], ['Reassure', 'Show timely proof to new visitors.']],
    ],
    'autoblog' => [
        'name' => 'Autoblog', 'tag' => 'Attract', 'accent' => 'pink',
        'headline' => 'Keep publishing useful content without losing your week.',
        'intro' => 'Plan and generate original long-form articles, organize your content library, and connect publishing destinations.',
        'outcome' => 'Build a consistent organic presence with a practical production system your team can review and control.',
        'features' => [
            ['Original article generation', 'Create complete drafts around your topic, tone, keywords, and audience.'],
            ['Post library', 'Manage ideas, drafts, and finished articles from one organized content hub.'],
            ['Topic and keyword guidance', 'Give every draft a clear search focus and editorial direction.'],
            ['Destination connections', 'Prepare content for the channels and sites where you publish.'],
            ['Review workflow', 'Keep humans in control before any content becomes part of your public brand.'],
            ['Content settings', 'Shape output around your business voice and publishing goals.'],
        ],
        'steps' => [['Brief', 'Define the topic, voice, and search intent.'], ['Review', 'Refine a complete original draft.'], ['Publish', 'Move approved content to its destination.']],
    ],
];
