<?php

namespace App\Support;

use App\Models\EngageCampaign;

class EngageTemplates
{
    /**
     * Ready-to-use campaign setups with copy, style, and targeting prefilled.
     */
    public static function all(): array
    {
        return [
            'free_shipping_bar' => [
                'label' => 'Free shipping bar',
                'blurb' => 'Slim top bar for a clear promo.',
                'category' => 'Bars',
                'swatch' => '#0f766e',
                'defaults' => [
                    'name' => 'Free shipping bar',
                    'type' => EngageCampaign::TYPE_BAR,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 10,
                    'headline' => 'Free shipping on orders over $50',
                    'body' => 'This week only — no code needed.',
                    'cta_label' => 'Shop now',
                    'cta_url' => '/',
                    'position' => 'top',
                    'brand_color' => '#0f766e',
                    'text_color' => '#ecfdf5',
                    'delay_ms' => 0,
                    'frequency_hours' => 12,
                    'device' => 'any',
                ],
            ],
            'flash_sale_bar' => [
                'label' => 'Flash sale bar',
                'blurb' => 'High-urgency strip for limited offers.',
                'category' => 'Bars',
                'swatch' => '#c2410c',
                'defaults' => [
                    'name' => 'Flash sale bar',
                    'type' => EngageCampaign::TYPE_BAR,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 20,
                    'headline' => '⚡ 24-hour flash sale',
                    'body' => 'Take 30% off — ends tonight.',
                    'cta_label' => 'Claim deal',
                    'cta_url' => '/pricing',
                    'position' => 'top',
                    'brand_color' => '#c2410c',
                    'text_color' => '#fff7ed',
                    'delay_ms' => 0,
                    'frequency_hours' => 6,
                    'device' => 'any',
                ],
            ],
            'welcome_popup' => [
                'label' => 'Welcome popup',
                'blurb' => 'Friendly hello with a primary CTA.',
                'category' => 'Popups',
                'swatch' => '#1d4ed8',
                'defaults' => [
                    'name' => 'Welcome popup',
                    'type' => EngageCampaign::TYPE_POPUP,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 5,
                    'headline' => 'Welcome — glad you’re here',
                    'body' => "Take a quick look around. We’ve put together everything you need to get started.",
                    'cta_label' => 'Explore',
                    'cta_url' => '/',
                    'position' => 'center',
                    'brand_color' => '#1d4ed8',
                    'text_color' => '#ffffff',
                    'delay_ms' => 1200,
                    'frequency_hours' => 72,
                    'device' => 'any',
                ],
            ],
            'discount_popup' => [
                'label' => 'Discount popup',
                'blurb' => 'Offer a code after a short delay.',
                'category' => 'Popups',
                'swatch' => '#7c2d12',
                'defaults' => [
                    'name' => 'Discount popup',
                    'type' => EngageCampaign::TYPE_POPUP,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 15,
                    'headline' => 'A little something for you',
                    'body' => 'Use code HELLO15 for 15% off your first order.',
                    'cta_label' => 'Start shopping',
                    'cta_url' => '/',
                    'position' => 'center',
                    'brand_color' => '#9a3412',
                    'text_color' => '#ffffff',
                    'delay_ms' => 4500,
                    'frequency_hours' => 168,
                    'device' => 'any',
                ],
            ],
            'help_slide' => [
                'label' => 'Help slide-in',
                'blurb' => 'Corner panel when visitors might need a nudge.',
                'category' => 'Slide-ins',
                'swatch' => '#0e7490',
                'defaults' => [
                    'name' => 'Help slide-in',
                    'type' => EngageCampaign::TYPE_SLIDE_IN,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 8,
                    'headline' => 'Need a hand?',
                    'body' => 'Our team is happy to walk you through options — no pressure.',
                    'cta_label' => 'Talk to us',
                    'cta_url' => '/contact',
                    'position' => 'bottom-right',
                    'brand_color' => '#0e7490',
                    'text_color' => '#ffffff',
                    'delay_ms' => 8000,
                    'frequency_hours' => 48,
                    'device' => 'desktop',
                ],
            ],
            'lead_form' => [
                'label' => 'Lead capture form',
                'blurb' => 'Name + email with a clean success state.',
                'category' => 'Forms',
                'swatch' => '#166534',
                'defaults' => [
                    'name' => 'Lead capture form',
                    'type' => EngageCampaign::TYPE_FORM,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 12,
                    'headline' => 'Get the guide',
                    'body' => 'Drop your email and we’ll send the playbook straight to your inbox.',
                    'cta_label' => 'Send it over',
                    'cta_url' => '',
                    'position' => 'center',
                    'brand_color' => '#166534',
                    'text_color' => '#ffffff',
                    'fields_name' => true,
                    'fields_email' => true,
                    'success_message' => 'You’re on the list — check your inbox shortly.',
                    'delay_ms' => 2500,
                    'frequency_hours' => 168,
                    'device' => 'any',
                ],
            ],
            'demo_form' => [
                'label' => 'Book a demo',
                'blurb' => 'Slide-in form for sales-ready visitors.',
                'category' => 'Forms',
                'swatch' => '#1e3a8a',
                'defaults' => [
                    'name' => 'Book a demo',
                    'type' => EngageCampaign::TYPE_FORM,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 18,
                    'headline' => 'See it live',
                    'body' => 'Tell us where to reach you and we’ll schedule a walkthrough.',
                    'cta_label' => 'Request demo',
                    'position' => 'bottom-right',
                    'brand_color' => '#1e3a8a',
                    'text_color' => '#ffffff',
                    'fields_name' => true,
                    'fields_email' => true,
                    'success_message' => 'Thanks — we’ll be in touch within one business day.',
                    'delay_ms' => 6000,
                    'frequency_hours' => 120,
                    'device' => 'any',
                    'url_contains' => '/pricing',
                ],
            ],
            'social_proof_toast' => [
                'label' => 'Social proof toast',
                'blurb' => 'Subtle “someone just…” notifications.',
                'category' => 'Toasts',
                'swatch' => '#334155',
                'defaults' => [
                    'name' => 'Social proof toast',
                    'type' => EngageCampaign::TYPE_TOAST,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 3,
                    'headline' => '',
                    'body' => '',
                    'toast_name' => 'Maya',
                    'toast_action' => 'just signed up',
                    'toast_location' => 'Austin, TX',
                    'position' => 'bottom-left',
                    'brand_color' => '#334155',
                    'text_color' => '#ffffff',
                    'delay_ms' => 5000,
                    'frequency_hours' => 2,
                    'device' => 'any',
                ],
            ],
            'purchase_toast' => [
                'label' => 'Purchase toast',
                'blurb' => 'Show recent activity to build trust.',
                'category' => 'Toasts',
                'swatch' => '#065f46',
                'defaults' => [
                    'name' => 'Purchase toast',
                    'type' => EngageCampaign::TYPE_TOAST,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 4,
                    'toast_name' => 'Jordan',
                    'toast_action' => 'purchased the Pro plan',
                    'toast_location' => '2 minutes ago',
                    'position' => 'bottom-left',
                    'brand_color' => '#065f46',
                    'text_color' => '#ffffff',
                    'delay_ms' => 7000,
                    'frequency_hours' => 1,
                    'device' => 'any',
                ],
            ],
            'updates_launcher' => [
                'label' => 'Updates launcher',
                'blurb' => 'Floating button that opens another campaign.',
                'category' => 'Launchers',
                'swatch' => '#0f172a',
                'defaults' => [
                    'name' => 'Updates launcher',
                    'type' => EngageCampaign::TYPE_LAUNCHER,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 1,
                    'launcher_label' => 'What’s new',
                    'position' => 'bottom-right',
                    'brand_color' => '#0f172a',
                    'text_color' => '#f8fafc',
                    'delay_ms' => 0,
                    'frequency_hours' => 0,
                    'max_displays' => 0,
                    'device' => 'any',
                ],
            ],
            'video_promo' => [
                'label' => 'Video promo popup',
                'blurb' => 'YouTube/Vimeo promo with CTA under the player.',
                'category' => 'Video',
                'swatch' => '#7c3aed',
                'defaults' => [
                    'name' => 'Video promo popup',
                    'type' => EngageCampaign::TYPE_VIDEO,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 16,
                    'headline' => 'Watch the 60-second overview',
                    'body' => 'See how teams ship faster — then claim your launch offer.',
                    'cta_label' => 'Claim offer',
                    'cta_url' => '/pricing',
                    'video_url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                    'position' => 'center',
                    'brand_color' => '#7c3aed',
                    'text_color' => '#ffffff',
                    'delay_ms' => 2000,
                    'frequency_hours' => 48,
                    'max_displays' => 3,
                    'device' => 'any',
                ],
            ],
            'video_product_demo' => [
                'label' => 'Product demo video',
                'blurb' => 'Feature walkthrough for pricing and product pages.',
                'category' => 'Video',
                'swatch' => '#0f766e',
                'defaults' => [
                    'name' => 'Product demo video',
                    'type' => EngageCampaign::TYPE_VIDEO,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 14,
                    'headline' => 'See it in action',
                    'body' => 'A short tour of the workflow your team will use every day.',
                    'cta_label' => 'Start free trial',
                    'cta_url' => '/signup',
                    'video_url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                    'position' => 'center',
                    'brand_color' => '#0f766e',
                    'text_color' => '#ecfdf5',
                    'delay_ms' => 3500,
                    'frequency_hours' => 72,
                    'max_displays' => 2,
                    'device' => 'any',
                    'url_contains' => '/pricing',
                ],
            ],
            'holiday_promo_bar' => [
                'label' => 'Holiday promo bar',
                'blurb' => 'Seasonal strip — show a few times, then stop.',
                'category' => 'Bars',
                'swatch' => '#9f1239',
                'defaults' => [
                    'name' => 'Holiday promo bar',
                    'type' => EngageCampaign::TYPE_BAR,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 25,
                    'headline' => 'Holiday sale — up to 40% off',
                    'body' => 'Ends Sunday. Free returns.',
                    'cta_label' => 'Shop sale',
                    'cta_url' => '/sale',
                    'position' => 'top',
                    'brand_color' => '#9f1239',
                    'text_color' => '#fff1f2',
                    'delay_ms' => 0,
                    'frequency_hours' => 12,
                    'max_displays' => 5,
                    'device' => 'any',
                ],
            ],
            'newsletter_popup' => [
                'label' => 'Newsletter popup',
                'blurb' => 'Email capture shown once per visitor.',
                'category' => 'Forms',
                'swatch' => '#4338ca',
                'defaults' => [
                    'name' => 'Newsletter popup',
                    'type' => EngageCampaign::TYPE_FORM,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 11,
                    'headline' => 'Join the list',
                    'body' => 'Tips, launches, and early access — no spam.',
                    'cta_label' => 'Subscribe',
                    'position' => 'center',
                    'brand_color' => '#4338ca',
                    'text_color' => '#ffffff',
                    'fields_name' => false,
                    'fields_email' => true,
                    'success_message' => 'You’re in — welcome aboard.',
                    'delay_ms' => 4000,
                    'frequency_hours' => 720,
                    'max_displays' => 1,
                    'device' => 'any',
                ],
            ],
            'urgency_toast' => [
                'label' => 'Urgency toast',
                'blurb' => 'Scarcity-style notification after a short delay.',
                'category' => 'Toasts',
                'swatch' => '#b45309',
                'defaults' => [
                    'name' => 'Urgency toast',
                    'type' => EngageCampaign::TYPE_TOAST,
                    'status' => EngageCampaign::STATUS_DRAFT,
                    'priority' => 6,
                    'toast_name' => 'Sam',
                    'toast_action' => 'just grabbed the last seat',
                    'toast_location' => 'moments ago',
                    'position' => 'bottom-left',
                    'brand_color' => '#b45309',
                    'text_color' => '#ffffff',
                    'delay_ms' => 9000,
                    'frequency_hours' => 4,
                    'max_displays' => 4,
                    'device' => 'any',
                ],
            ],
        ];
    }

    public static function get(string $key): ?array
    {
        return self::all()[$key] ?? null;
    }

    public static function applyToCampaign(array $defaults): EngageCampaign
    {
        $campaign = new EngageCampaign([
            'name' => $defaults['name'] ?? 'New campaign',
            'type' => $defaults['type'] ?? EngageCampaign::TYPE_BAR,
            'status' => $defaults['status'] ?? EngageCampaign::STATUS_DRAFT,
            'priority' => $defaults['priority'] ?? 0,
        ]);

        $campaign->content = [
            'headline' => $defaults['headline'] ?? '',
            'body' => $defaults['body'] ?? '',
            'cta_label' => $defaults['cta_label'] ?? '',
            'cta_url' => $defaults['cta_url'] ?? '',
            'position' => $defaults['position'] ?? 'top',
            'success_message' => $defaults['success_message'] ?? 'Thanks — we will be in touch.',
            'fields' => [
                'name' => (bool) ($defaults['fields_name'] ?? false),
                'email' => (bool) ($defaults['fields_email'] ?? ($defaults['type'] ?? '') === EngageCampaign::TYPE_FORM),
            ],
            'toast' => [
                'name' => $defaults['toast_name'] ?? '',
                'action' => $defaults['toast_action'] ?? '',
                'location' => $defaults['toast_location'] ?? '',
            ],
            'launcher_label' => $defaults['launcher_label'] ?? 'Updates',
            'opens_campaign_id' => $defaults['opens_campaign_id'] ?? null,
            'video_url' => $defaults['video_url'] ?? '',
        ];

        $campaign->targeting = [
            'url_contains' => $defaults['url_contains'] ?? '',
            'delay_ms' => (int) ($defaults['delay_ms'] ?? 0),
            'frequency_hours' => (int) ($defaults['frequency_hours'] ?? 24),
            'max_displays' => (int) ($defaults['max_displays'] ?? 0),
            'device' => $defaults['device'] ?? 'any',
        ];

        $campaign->style = [
            'brand_color' => $defaults['brand_color'] ?? '#2563eb',
            'text_color' => $defaults['text_color'] ?? '#ffffff',
        ];

        return $campaign;
    }

    public static function grouped(): array
    {
        return collect(self::all())
            ->map(fn ($tpl, $key) => $tpl + ['key' => $key])
            ->groupBy('category')
            ->all();
    }
}
