@extends('layouts.app')
@section('title',$form->exists?'Edit form':'New form')
@section('content')
@include('modules.forms._nav')
<div class="d-flex justify-content-between mb-4"><h4>{{ $form->exists?'Edit form':'Customize form' }}</h4><a class="btn btn-outline-secondary" href="{{ route('forms.forms.index') }}">Back</a></div>
<form method="POST" action="{{ $form->exists?route('forms.forms.update',$form):route('forms.forms.store') }}" class="card card-body">@csrf @if($form->exists)@method('PUT')@endif
<div class="row g-3"><div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" value="{{ old('name',$form->name) }}" required></div><div class="col-md-3"><label class="form-label">Type</label><select class="form-select" name="type">@foreach(App\Models\Form::types() as $v=>$l)<option value="{{ $v }}" @selected(old('type',$form->type)===$v)>{{ $l }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status">@foreach(App\Models\Form::statuses() as $v=>$l)<option value="{{ $v }}" @selected(old('status',$form->status)===$v)>{{ $l }}</option>@endforeach</select></div></div>
<hr><h5>Fields</h5><div id="fields">@foreach(old('fields',$form->fields??[]) as $i=>$field)<div class="row g-2 align-items-end field-row mb-2"><div class="col"><label>Key</label><input class="form-control" name="fields[{{ $i }}][key]" value="{{ $field['key'] }}" required></div><div class="col"><label>Label</label><input class="form-control" name="fields[{{ $i }}][label]" value="{{ $field['label'] }}" required></div><div class="col"><label>Type</label><select class="form-select" name="fields[{{ $i }}][type]">@foreach(['text','email','textarea','select','rating','nps'] as $t)<option @selected($field['type']===$t)>{{ $t }}</option>@endforeach</select></div><div class="col-auto"><label><input type="checkbox" name="fields[{{ $i }}][required]" value="1" @checked($field['required']??false)> Required</label></div><div class="col-auto"><button type="button" class="btn btn-outline-danger remove">×</button></div></div>@endforeach</div><button type="button" id="add" class="btn btn-outline-secondary btn-sm align-self-start">Add field</button>
<div class="mt-3"><label class="form-label">Thank-you message</label><textarea class="form-control" name="thank_you">{{ old('thank_you',$form->thank_you) }}</textarea></div><div class="mt-4 d-flex justify-content-between">@if($form->exists)<button form="delete-form" class="btn btn-outline-danger" onclick="return confirm('Delete this form?')">Delete</button>@endif<button class="btn btn-primary">Save form</button></div></form>
@if($form->exists)<form id="delete-form" method="POST" action="{{ route('forms.forms.destroy',$form) }}">@csrf @method('DELETE')</form>@endif
@push('scripts')<script>let n=document.querySelectorAll('.field-row').length;document.getElementById('add').onclick=()=>{document.getElementById('fields').insertAdjacentHTML('beforeend',`<div class="row g-2 align-items-end field-row mb-2"><div class="col"><label>Key</label><input class="form-control" name="fields[${n}][key]" required></div><div class="col"><label>Label</label><input class="form-control" name="fields[${n}][label]" required></div><div class="col"><label>Type</label><select class="form-select" name="fields[${n}][type]"><option>text</option><option>email</option><option>textarea</option><option>select</option><option>rating</option><option>nps</option></select></div><div class="col-auto"><label><input type="checkbox" name="fields[${n}][required]" value="1"> Required</label></div><div class="col-auto"><button type="button" class="btn btn-outline-danger remove">×</button></div></div>`);n++};document.addEventListener('click',e=>{if(e.target.classList.contains('remove'))e.target.closest('.field-row').remove()})</script>@endpush
@endsection
